### PR TITLE
[SUBMARINE-193] Add submarine-web/server to submarine-dist

### PR DESCRIPTION
**Pull request by liuxunorg**
### What is this PR for?
Package the submarine Web dist folder into the war file, When the submarine server is started, by loading the war file, Start the submarine web front end.

### What type of PR is it?
[Feature]

### What is the Jira issue?
* https://issues.apache.org/jira/browse/SUBMARINE-193

### How should this be tested?
* [CI Pass](https://travis-ci.org/liuxunorg/hadoop-submarine/builds/590237404)

### Screenshots (if appropriate)
```
.
|____LICENSE
|____licenses
| |____LICENSE-asm.txt
| |____LICENSE-hamcrest.txt
| |____LICENSE-jgit.txt
| |____LICENSE-pagehelper.txt
| |____LICENSE-paranamer.txt
| |____LICENSE-protobuf.txt
| |____LICENSE-slf4j.txt
| |____LICENSE-tony.txt
|____NOTICE
|____submarine-all-0.3.0-SNAPSHOT-hadoop-2.9.jar
|____submarine-core-0.3.0-SNAPSHOT.jar
|____tony-core-0.3.21.jar
|____tony-runtime-0.3.0-SNAPSHOT.jar
|____workbench
| |____lib
| | |____aopalliance-repackaged-2.5.0-b42.jar
| | |____asm-3.3.1.jar
| | |____cglib-2.2.2.jar
| | |____commons-configuration-1.10.jar
| | |____.......
| | |____mysql-connector-java-5.1.39.jar
| | |____websocket-servlet-9.4.18.v20190429.jar
| |____submarine-server-0.3.0-SNAPSHOT.jar
| |____submarine-web-0.3.0-SNAPSHOT.war
```

### Questions:
* Does the licenses files need update? Yes/No
* Is there breaking changes for older versions? Yes/No
* Does this needs documentation? Yes/No

### CODE REVIEW

**Comment by jojochuang** [comment]
I am assuming this is technically a backward incompatible change, since it removes the artifact submarine-server-*-shade.jar to submarine-server-*.jar.

I think this is okay given this is an early stage project. Backward incompatible change is acceptable. Should we add release note to the jira/label the jira as backward incompatible?

**Comment by tangzhankun** [comment]
@liuxunorg , One question, is it possible to package the lib jars into server.jar or web.war?

**Comment by liuxunorg** [comment]
@tangzhankun, submarine-web.war is web front-end, It contains html/JS. if submarine-server.jar contains all depends jar, we can't see depends jar's version.
submarine-server-<version>.jar is only used by workbench, put all depends jar into submarine-server-shaded.jar, Also.

**Comment by jojochuang** [comment]
LGTM

**Pull request closed without merging**
