### PR TITLE
[SUBMARINE-205] Modify license format

### PR DESCRIPTION
**Pull request by LinhaoZhu**
### What is this PR for?
In non-java files, the format of license is not in accordance with the specification and needs to be modified, including parts of xxxMapper.xml and pom.xml

### What type of PR is it?
[ Improvement ]

### Todos
* [ ] - Task

### What is the Jira issue?
* [SUBMARINE-205](https://issues.apache.org/jira/browse/SUBMARINE-205)

### How should this be tested?
* [CI Pass](https://travis-ci.org/LinhaoZhu/hadoop-submarine/builds/595014468)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jojochuang** [comment]
We are we changing the license text itself? According to https://www.apache.org/legal/src-headers.html, the original text 

> Licensed to the Apache Software Foundation (ASF) ...

 is applicable to  works submitted directly to the ASF by the copyright owner or owner's agent, which is exactly the case here.

**Comment by LinhaoZhu** [comment]
> We are we changing the license text itself? According to https://www.apache.org/legal/src-headers.html, the original text
> 
> > Licensed to the Apache Software Foundation (ASF) ...
> 
> is applicable to works submitted directly to the ASF by the copyright owner or owner's agent, which is exactly the case here.
@jojochuang Thank you for reviewing the code.
I am not sure whether there is a difference between the two licenses header.
I just found that there are two different ways of writing license header, and I want to unify them into one standard,Therefore, I made modifications according to the http://www.apache.org/licenses/LICENSE-2.0#apply
If there is a clear plan, please guide it. Thank you once again.

**Comment by jojochuang** [comment]
Thanks. This is the code submitted to Submarine, which is a project governed by Apache Software Foundation. So please following the license text in https://www.apache.org/legal/src-headers.html

**Comment by jiwq** [comment]
Agree with @jojochuang. Thanks for @jojochuang help to point to this and gave the right link.
@LinhaoZhu , can you help to check all the files and fix it?

**Comment by LinhaoZhu** [comment]
@jiwq ,I think I will fix all the unreasonable license text in the workbench-server, other files I have to take time to complete. @jojochuang We are following this license text? Or wait for later project upgrade will have change.

**Comment by LinhaoZhu** [comment]
@jojochuang @jiwq, I have already modified completed and resubmit, please help to confirm again, thank you!

**Comment by tangzhankun** [comment]
Thanks, @LinhaoZhu . LGTM. I will merge it soon.

**Pull request closed without merging**
